### PR TITLE
Added 63950 and 63998 to carrier prefixes for Smart, Philippines

### PR DESCRIPTION
**Pull request by enriquejr**

### CODE REVIEW

**Comment by mihaelacr-google** [comment]
Can you please provide us with some evidence supporting that these prefixes are allocated for the Smart carrier? 

Thanks :)

**Comment by enriquejr** [comment]
Sorry, I only have a corporate email. I may have to seek permission as well to share that email.

**Comment by enriquejr** [comment]
I secured an email from a representative of Smart confirming this update. Can you give me an email to forward it to?

**Comment by mihaelacr-google** [comment]
Please forward to mihaelacr@google.com .

Thanks!

**Comment by dlyongemallo** [comment]
Do you have any information on the lengths of the numbers with these prefixes?

**Comment by dlyongemallo** [comment]
Actually, we already support 998. We just need info on the length of 950 prefix numbers. Thanks.

**Comment by enriquejr** [comment]
The length of mobile numbers in the Philippines is always 10 excluding
country code and including prefix.

On Thu, Apr 9, 2015 at 11:09 PM, David Yonge-Mallo <notifications@github.com

**Comment by roes** [comment]
This has been fixed.

**Pull request closed without merging**
