### PR TITLE
Update 212.txt

### PR DESCRIPTION
**Pull request by NeverMindNever**
Hello, 

I noticed that the number +212682 was not detected as correct by the library i checked the national numbering plan for the governing authority and i saw it was valid number , 

After checking the code i saw many mistakes, I made changes according to the file from ANRT that is published on the website under : 

https://www.anrt.ma/sites/default/files/blocs_de_numeros_par_operateur_juillet_2016.pdf

Best regards,

Alaa TOUNSADI

### CODE REVIEW

**Comment by NeverMindNever** [comment]
I signed it

**Comment by andyst** [comment]
Please try again. A) the bot didn't automatically confirm it, B) I checked it too right now and your Github handle (NeverMindNever) isn't in the system yet.

**Comment by penmetsaa** [comment]
@Alaa TOUNSADI,

Thanks for providing all the details we need! :)

This pull request looks perfect.
Please sign the CLA so that we can go ahead and merge this pull request.

Regarding 682 range, we've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by NeverMindNever** [comment]
I signed it!

**Comment by penmetsaa** [comment]
Thanks Alaa TOUNSADI.
LGTM, we'll merge as soon as possible.

**Comment by keghani** [comment]
Released in 7.6.0.

**Pull request merged**
