### PR TITLE
Use protobuf-lite

### PR DESCRIPTION
**Pull request by azzar1**
Use libprotobuf-lite in cpp/

### CODE REVIEW

**Comment by azzar1** [comment]
I signed it!

**Comment by keghani** [comment]
Hi @azzar1! What issue does this fix? I can build C++ with the current setup.

**Comment by azzar1** [comment]
Hi @keghani, for what I see libphonenumber does not need to be build with the full libprotobuf. the lite version seems to be enough. So I was wondering why libphonenumber still links to the full version.

**Comment by keghani** [comment]
Mostly because there's no issue with this as far as I'm aware. Linking against libprotobuf-lite would require us to re-test everything and update the [README](https://github.com/googlei18n/libphonenumber/blob/master/cpp/README), and it's hard to invest in this now considering nothing's broken.

**Pull request closed without merging**
