### PR TITLE
Add GB (+44) Carrier Info

### PR DESCRIPTION
**Pull request by giggsey**
Source: [Ofcom S7 Numbering](http://www.ofcom.org.uk/static/numbering/)

Run through https://github.com/giggsey/GBCarrierGenerator to extract the data and compress it

### CODE REVIEW

**Comment by keghani** [comment]
Thanks for contributing @giggsey!

We actually have a PR in progress for this, after it's done if there are any changes would you mind sending a new PR?

**Comment by giggsey** [comment]
Sure. I'll close this for now then.

**Comment by giggsey** [comment]
@keghani Just wondering on the internal progress of this PR?

**Comment by keghani** [comment]
@giggsey I just checked and it's still in progress. This is actually a large change, I hadn't noticed! Thanks for your patience.

**Comment by giggsey** [comment]
Sorry to bump this again, but has there been any progress?

It'll be nice to have this data for the UK.

**Comment by kkeshava** [comment]
Hi,
Thanks for bumping this again :)  Sorry for the delay. It is not a straightforward change for us. If possible we add only commonly used names for carriers. We consider validation / parsing issues as priority ones. We will prioritize this and try to fix mostly in an upcoming release. We will update this issue when it is part of the release. It would be great if you can review it that time :)

**Comment by giggsey** [comment]
@kkeshava I can translate the company names into trading names if that helps.

The big '4' (EE, vodafone, O2 and Three) cover the majority of the number ranges.

**Comment by giggsey** [comment]
Related to #1080

**Pull request closed without merging**
