### PR TITLE
Metadata updates for release 7.7.3

### PR DESCRIPTION
**Pull request by penmetsaa**
Oct 26, 2016: libphonenumber-7.7.3

Internal changes:
 - Fixed Phonemetadata.java not to merge from a NumberFormat's unset bool
   national_prefix_optional_when_formatting.
 - Added MetadataFilter, an internal API which is under development and subject
   to backwards-incompatible changes without notice or guarantees.

Metadata changes:
 - Updated phone metadata for region code(s):
   882, AG, AI, AS, BB, BM, BR, BS, CA, DM, DO, GD, GU, HU, IN, JM, KN, KY, KZ,
   LC, MP, MS, PR, SX, TC, TR, TT, UG, US, VC, VG, VI
 - Updated short number metadata for region code(s): UY
 - New geocoding data for country calling code(s): 1463 (en)
 - Updated geocoding data for country calling code(s): 7 (en, ru)
 - Updated carrier data for country calling code(s):
   91 (en), 256 (en), 1876 (en)

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1400)

### CODE REVIEW

**Comment by penmetsaa** [comment]
@keghani,
Short number update is done only for UY in this release. For other countries we have included possibleLengths tag. Can we remove these from java/release_notes.txt and PR description?

**Comment by keghani** [comment]
@penmetsaa Yes please, good catch :)

**Comment by penmetsaa** [comment]
Done Keghani. 
Please review this PR.

**Comment by lararennie** [comment]
I think we should, yes.

26. okt. 2016 7.04 a.m. skrev "penmetsaa" <notifications@github.com>:

**Pull request merged**
