### PR TITLE
update for Chinese phonenums geo data 8617+

### PR DESCRIPTION
**Pull request by tg123**
1. more 170+ data
1. minor data update

### CODE REVIEW

**Comment by roes** [comment]
@jias0001: Do you mind having a look at this one?

**Comment by jias0001** [comment]
Sure. I took a quick look and it looks good to me.

**Comment by dlyongemallo** [comment]
This should be in the next release.

**Comment by andyst** [comment]
Thanks! This is in libphonenumber 7.0.7.

**Pull request closed without merging**
