### PR TITLE
Use protobufs found by cmake

### PR DESCRIPTION
**Pull request by berkus**

### CODE REVIEW

**Comment by berkus** [comment]
I've signed it!

**Comment by keghani** [comment]
Thanks! Please link to an issue with a clear description of what this intends to fix. See [the PR contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#pull-requests).

**Comment by berkus** [comment]
I've no link to issue, i was helping the user fix their problem with protobufs - the cmake way is better to detect it, the current in the code seemed to assume protobufs would be copied INSIDE this repo?

**Comment by berkus** [comment]
Quote from user:
> кто-нибудь сталкивался при попытке сбилдить пакет с  PROTOC_BIN-NOTFOUND: Command not found ? Притом, что protobuf и protobuf compiler установлены (через apt-get).

They assumed to install protobuf-dev which was then not found.

**Comment by keghani** [comment]
Do [these instructions](http://github.com/googlei18n/libphonenumber/blob/master/cpp/README) not work for them?

Where did "the user" report this?

I'm not sure how to verify that this will solve their problem, and not break other people's setup.

**Comment by keghani** [comment]
Is olesyaksyon@ from https://github.com/googlei18n/libphonenumber/issues/1864 your user?
Using Google Translate, from the snippet of the issue you shared, I can't tell that it's an issue with our file rather than the user's setup. We should have a series of commands that would reproduce the issue on their setup before we consider changing what appears to be working for other users.

**Comment by berkus** [comment]
Yes, that's her.

**Comment by berkus** [comment]
@keghani 
> Do these instructions not work for them?

no, she apparently followed this step by step.

**Comment by berkus** [comment]
My idea is to let cmake manage the protobufs installation, in most cases it knows better where to look.

**Comment by keghani** [comment]
She said on that issue that she's got it working now.

**Comment by olesyaksyon** [comment]
hello. yes, it is working because I installed it with apt-get. but it was not builded from source. here is the thing is about building from source.

**Comment by keghani** [comment]
Thanks for confirming @olesyaksyon!

We don't want to require that anything be built from source. Released dependencies are more stable and I still don't see an issue with anyone not being able to build our libraries, so I'm going to close this.

If there are issues, please file an issue as mentioned in our contribution guidelines, describing clearly how to reproduce it. If it's something to do with our scripts or setup then we'd love to fix it. If it's to do with people's setup we will try to provide support as long as we can see how to reproduce it.

For personal preferences you can always make your own fork and maintain your own CMakeLists.txt the way you prefer.

**Comment by berkus** [comment]
>  I still don't see an issue with anyone not being able to build our libraries

Thats a great attitude, thank you!

**Pull request closed without merging**
