### PR TITLE
Rpm packaging fixed

### PR DESCRIPTION
**Pull request by dimbleby**
A fixed version of #571.  

Once again, my apologies for screwing this up last time.

### CODE REVIEW

**Comment by keghani** [comment]
Thanks for this patch!

It seems to work, though I don't understand this file much - and I don't know whether it will do the RPM packaging correctly but happy to trust you.
If you can do the following I'll see if I can find a more knowledgeable person to review, otherwise we'll just merge as long as it doesn't break our build / tests:

*   Sign the CLA - you should get a notificaton from googlebot shortly on this thread
*   Merge changes from upstream

**Comment by dimbleby** [comment]
@keghani: 

I've merged the latest master code into this pull request.

I confess that I don't remember much about this one myself!  But it does indeed seem to work - I've been using RPMs packaged this way for some time - and I guess I trust myself-of-two-years-ago too.

I'll get back to you on whether or not I'm willing / able to sign the CLA.

**Comment by keghani** [comment]
Hi @dimbleby,

Will you be willing / able to sign the CLA? Without it we cannot accept this patch and will have to close it.

**Comment by dimbleby** [comment]
Still working on it... apologies for the delay.

**Comment by dimbleby** [comment]
I signed it!

**Comment by dimbleby** [comment]
I believe I've signed the CLA, but "waiting for status to be reported"...

@keghani is it possible to kick the bot somehow, or otherwise determine what problem it sees?

**Comment by keghani** [comment]
Hi @dimbleby,
I've noticed that too, sometimes I've had to close and re-open issues to kick off the CLA bot.
But in this case, I don't think that will help - I can check CLA signatures manually, and I still don't see one associated with your GitHub username.

The email that you signed the CLA with - is it added to your GitHub account [like this](https://help.github.com/articles/adding-an-email-address-to-your-github-account/)?
Or if you're covered by corporate CLA, please ask the administrators of the Google Group to add your email address to that group, which should also be an email address on your account. [Details](https://cla.developers.google.com/about)

**Comment by dimbleby** [comment]
Hi @keghani,
It is a corporate CLA, and my github email address is a member of the appropriate group.

Anything I can do to verify that this is all set up correctly?

**Comment by keghani** [comment]
I still can't find it. I'll close and re-open this to see if the bot has a different answer.

To verify, I would go through all of [the steps](https://cla.developers.google.com/about) again and make sure they got through. E.g. was the agreement already reviewed and approved by someone at Google?

**Comment by dimbleby** [comment]
@keghani: Well, this is frustrating.

* you were right, Google had not got back to us 
* so we sent a chasing email on 16th October
* but still no reply - and now we've instead received a time-out on our CLA

Anything you can do to help?

**Comment by keghani** [comment]
Thanks for updating us!
I don't know what's going on with the process. I haven't heard of a time-out with the CLA. Sorry this is frustrating, I'm not the right person to troubleshoot either. I would try one of:

*   Retry everything.
*   Send an email first to ask about turnaround time (e.g. they could have public holidays - or something like our having a freeze period on this repository near end of year).

**Comment by dimbleby** [comment]
Thanks.  

We've emailed the cla-submissions address already, with no reply.  Can you recommend anyone else we can ask about this?

**Comment by keghani** [comment]
Which corporate CLA did you try? (Google? Android?)

**Comment by dimbleby** [comment]
Google

**Comment by cflewis** [comment]
Hi David:
Can you please email me at cflewis@google.com so I can take a look? Please let me know what company is supposed to have signed the CLA that you are covered under.

Thank you!

**Comment by dimbleby** [comment]
Hi @keghani , 

I've just spotted that my view of [this page](https://cla.developers.google.com/clas) does now say that I am covered by the expected coroprate CLA.  Can we have another go at kicking the bot, please?

**Comment by dimbleby** [comment]
oh, apparently that comment was enough.  yay!

**Comment by keghani** [comment]
Great, looks good! Thanks so much for sticking with it!

**Comment by Flamefire** [comment]
This is actually broken. Adding ` -m32` after `porject` may mess up a lot. E.g. CMAKE_SIZEOF_VOID_P will still be 8. Why add it as an option anyway? It is the users choice when invoking it by using a toolchain file or setting the flags accordingly. If you want to query the number of bits check CMAKE_SIZEOF_VOID_P

**Pull request merged**
