### PR TITLE
Move common metadata loading logic into MetadataManager, removing synchronization everywhere

### PR DESCRIPTION
**Pull request by keghani**
** Note for reviewers, do not copy into final commit **
cl/137686080
b/30158468
b/30807096

pkgdiff:
~keghani/GitHub_diffs/f51e431/pkgdiff_reports/cpp-build/1.0-SNAPSHOT-jar-with-dependencies_to_1.0-SNAPSHOT-jar-with-dependencies/changes_report.html
~keghani/GitHub_diffs/f51e431/pkgdiff_reports/java-build/1.0-SNAPSHOT-jar-with-dependencies_to_1.0-SNAPSHOT-jar-with-dependencies/changes_report.html

The jars picked up some .class changes since https://github.com/googlei18n/libphonenumber/pull/1432.

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1411)

### CODE REVIEW

**Comment by lararennie** [comment]
Review status: 0 of 8 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 70 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_UQF3IO8Ta20UqOT8:-KV_UQF3IO8Ta20UqOT9:bd5xrrv) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L70)):*
> countryCodeSet

I think we should rename this; alternateFormatCountryCodes instead?

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 75 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_U_5qVDhYhkH1bMp8:-KV_U_5qVDhYhkH1bMp9:bhvdbzk) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L75)):*
> regionCodeSet
And this one: shortNumberRegionCodes

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 100 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VKQS0MnOLs4dGazS:-KV_VKQS0MnOLs4dGazT:bbr60r4) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L100)):*
> ```Java
> 
>   /**
>    * @param key  the region code or the country calling code
> ```

Maybe say just: the lookup key for the provided map, typically a region code or a country calling code
Otherwise it sounds like it would work with the wrong one.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 101 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VduENbcTossiYdhl:-KV_VduENbcTossiYdhm:b-tjituj) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L101)):*
> ```Java
>   /**
>    * @param key  the region code or the country calling code
>    * @param map  the map to contain the mapping from {@code key} to the corresponding metadata
> ```

the map containing mappings of already loaded metadata to their key?

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 102 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VTe48nv0m1LFRLji:-KV_VTe48nv0m1LFRLjj:b-bt7cap) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L102)):*
> ```Java
>    * @param key  the region code or the country calling code
>    * @param map  the map to contain the mapping from {@code key} to the corresponding metadata
>    * @param filePrefix the prefix of the file to load metadata from
> ```

extra space before the

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 115 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VqV24uj1Bl3kO4XC:-KV_VqV24uj1Bl3kO4XD:bww4pir) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L115)):*
> ```Java
>     List<PhoneMetadata> metadataList = getMetadataFromFileName(fileName, metadataLoader);
>     if (metadataList.size() > 1) {
>       logger.log(Level.WARNING, "invalid metadata (too many entries): " + fileName);
> ```

Can you say "more than one metadata in file " + fileName instead? I initially thought there were multiple files and thought "how could that be?"

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 119 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_W5R-yCWFcVODCIr_:-KV_W5R-yCWFcVODCIra:b-x3ejdg) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L119)):*
> ```Java
>     metadata = metadataList.get(0);
>     PhoneMetadata oldValue = map.putIfAbsent(key, metadata);
>     return (oldValue != null) ? oldValue : metadata;
> ```

so this should usually return null right, unless there was a competing thread, in which case they both try and put stuff in, so returning the one already in the map is better? Why do we not just always return metadata? They should be the same? We won't have two threads putting *different* things in the map for the same file?

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 126 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_WUDnI1a-xxDzBTxr:-KV_WUDou1eNKO75vRtV:b-376gcv) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L126)):*
> ```Java
>     static SingleFileMetadataMaps load(String fileName, MetadataLoader metadataLoader) {
>       List<PhoneMetadata> metadataList = getMetadataFromFileName(fileName, metadataLoader);
>       Map<String, PhoneMetadata> stringMap = new HashMap<String, PhoneMetadata>();
> ```

stringMap and intMap; regionCodeToMetadata and countryCallingCodeToMetadata?

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 143 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_W_y-UwHUAvmqs8U-:-KV_W_y-UwHUAvmqs8U0:b-x7u5u0) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L143)):*
> ```Java
>     // For phone number metadata, the region code "001" is excluded, since that is used for the
>     // non-geographical phone number entities.
>     private final Map<String, PhoneMetadata> stringMap;
> ```

Same here re var name. regionCodeMap even?

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/SingleFileMetadataSourceImpl.java, line 36 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_XauJQsVMkGn9LHlS:-KV_XauJQsVMkGn9LHlT:b-ih6wm6) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/SingleFileMetadataSourceImpl.java#L36)):*
> ```Java
>       new AtomicReference<MetadataManager.SingleFileMetadataMaps>();
> 
>   // It is assumed that metadataLoader is not null. Checks should happen before passing here.
> ```

passing here; before passing it in here?

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/SingleFileMetadataSourceImpl.java, line 58 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_XlCvUN_Ge2WXg9cd:-KV_XlCvUN_Ge2WXg9ce:btdahyw) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/SingleFileMetadataSourceImpl.java#L58)):*
> ```Java
>     // A country calling code is non-geographical if it only maps to the non-geographical region
>     // code, i.e. RegionCode.UN001. If this is true of the given country calling code, then we will
>     // return null here. If not for the atomic reference, such as if we were loading in multiple
> ```

I'm confused: you will return null if it maps to UN001?
Also RegionCode.UN001 in comment should be probably "001" string - RegionCode is a testing class only. 

---

*[java/libphonenumber/test/com/google/i18n/phonenumbers/MetadataManagerTest.java, line 26 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_Y8ae_S0GdW9UO1x8:-KV_Y8ae_S0GdW9UO1x9:b-du6snf) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/test/com/google/i18n/phonenumbers/MetadataManagerTest.java#L26)):*
> ```Java
>  * Some basic tests to check that metadata can be correctly loaded.
>  */
> public final class MetadataManagerTest extends TestCase {
> ```

Do we usually make tests final? I mean, no one usually extends them anyway - what do we do for the rest?

---

*[java/libphonenumber/test/com/google/i18n/phonenumbers/SingleFileMetadataSourceImplTest.java, line 28 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_YTeZijOD_CPLQzg7:-KV_YTeZijOD_CPLQzg8:b-fln389) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/test/com/google/i18n/phonenumbers/SingleFileMetadataSourceImplTest.java#L28)):*
> ```Java
>  */
> public final class SingleFileMetadataSourceImplTest extends TestCase {
>   private static final SingleFileMetadataSourceImpl missingFileSource =
> ```

MISSING_FILE_SOURCE? It's kind of a constant :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by keghani** [comment]
Review status: 0 of 9 files reviewed at latest revision, 13 unresolved discussions.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 70 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_UQF3IO8Ta20UqOT8:-KVeurcPaQmyXsQmQJvg:b-37lxtb) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L70)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> > countryCodeSet
> 
> I think we should rename this; alternateFormatCountryCodes instead?
</details>
Done. I made alternateFormats instead of alternateFormat to be consistent with other names.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 75 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_U_5qVDhYhkH1bMp8:-KVeuwin4dsjaRFqs2n1:b7uhhll) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L75)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> > regionCodeSet
> And this one: shortNumberRegionCodes
</details>
Done. I made shortNumberMetadata instead of shortNumber to be consistent with other names.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 100 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VKQS0MnOLs4dGazS:-KVev-o4oVmtyDDT5QxR:b-896fix) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L100)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> Maybe say just: the lookup key for the provided map, typically a region code or a country calling code
> Otherwise it sounds like it would work with the wrong one.
</details>
Done.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 101 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VduENbcTossiYdhl:-KVev09a1ZB1WD_meECb:bumywys) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L101)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> the map containing mappings of already loaded metadata to their key?
</details>
They're not always already loaded; if already loaded we return, if not we load asynchronously, and once we've loaded we set it atomically if it's still unset by then.
The user of the API has to pass in the map that they want to contain the key.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 102 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VTe48nv0m1LFRLji:-KVf4mMXPRqUXShjqeT8:b-896fix) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L102)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> extra space before the
</details>
Done.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 115 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VqV24uj1Bl3kO4XC:-KVf4nRSvV-viayYM8eQ:b-896fix) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L115)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> Can you say "more than one metadata in file " + fileName instead? I initially thought there were multiple files and thought "how could that be?"
</details>
Done.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 119 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_W5R-yCWFcVODCIr_:-KVew471g2PKFZk1vCRD:b-son38v) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L119)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> so this should usually return null right, unless there was a competing thread, in which case they both try and put stuff in, so returning the one already in the map is better? Why do we not just always return metadata? They should be the same? We won't have two threads putting *different* things in the map for the same file?
</details>
map.putIfAbsent will return null if the value wasn't already loaded: https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html#putIfAbsent(K,%20V)
I think that if we just said "return metadata;", the method may return (to some thread) before metadata is in the map since it's already computed.
We want to complete the putIfAbsent call, i.e. we want to compute oldValue, before we return anything.
If you're interested we should ask @hagbard, he explained this and at the time I had understood it.

What's happening (in English):
- If map doesn't have the metadata, load the metadata
- Put the metadata in the map atomically, while (in the same atom) checking that it wasn't set in the meantime
- If it was indeed set in the meantime get what was set

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 126 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_WUDnI1a-xxDzBTxr:-KVezoP_SFI7QZ8kk1_h:b-896fix) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L126)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> stringMap and intMap; regionCodeToMetadata and countryCallingCodeToMetadata?
</details>
Done.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 143 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_W_y-UwHUAvmqs8U-:-KVf0BxNhBTwJY840G82:bp40nwx) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L143)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> Same here re var name. regionCodeMap even?
</details>
Done. (used earlier suggestion)

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/SingleFileMetadataSourceImpl.java, line 36 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_XauJQsVMkGn9LHlS:-KVf0YACKCOlp9fNP7ch:b-896fix) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/SingleFileMetadataSourceImpl.java#L36)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> passing here; before passing it in here?
</details>
Done.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/SingleFileMetadataSourceImpl.java, line 58 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_XlCvUN_Ge2WXg9cd:-KVf316VKe7S2Rf5NRem:b-m828ez) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/SingleFileMetadataSourceImpl.java#L58)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> I'm confused: you will return null if it maps to UN001?
> Also RegionCode.UN001 in comment should be probably "001" string - RegionCode is a testing class only. 
</details>
Done (was a typo, needed a "not")

---

*[java/libphonenumber/test/com/google/i18n/phonenumbers/MetadataManagerTest.java, line 26 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_Y8ae_S0GdW9UO1x8:-KVf3NKeSOA6Z2n7xqkX:bc0s05a) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/test/com/google/i18n/phonenumbers/MetadataManagerTest.java#L26)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> Do we usually make tests final? I mean, no one usually extends them anyway - what do we do for the rest?
</details>
Changed to be without final. MetadataFilterTest was the only existing test file with "final class".

FWIW We do have test files that we ourselves extend, like https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/test/com/google/i18n/phonenumbers/TestMetadataTestCase.java.

---

*[java/libphonenumber/test/com/google/i18n/phonenumbers/SingleFileMetadataSourceImplTest.java, line 28 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_YTeZijOD_CPLQzg7:-KVf3vJlHpripsyRaNPB:b-b1s75h) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/test/com/google/i18n/phonenumbers/SingleFileMetadataSourceImplTest.java#L28)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> MISSING_FILE_SOURCE? It's kind of a constant :)
</details>
Thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by keghani** [comment]
BTW - Please don't merge when you're happy, I still need to do last sanity checks with pkgdiff and the generated stuff with the final snapshot :)

**Comment by keghani** [comment]
Review status: 0 of 9 files reviewed at latest revision, 13 unresolved discussions.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 119 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_W5R-yCWFcVODCIr_:-KVfEEW5HhcgPfx0w9uY:b-jomy16) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L119)):*
<details><summary><i>Previously, keghani (Keghani Kouzoujian) wrote…</i></summary>
> map.putIfAbsent will return null if the value wasn't already loaded: https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html#putIfAbsent(K,%20V)
> I think that if we just said "return metadata;", the method may return (to some thread) before metadata is in the map since it's already computed.
> We want to complete the putIfAbsent call, i.e. we want to compute oldValue, before we return anything.
> If you're interested we should ask @hagbard, he explained this and at the time I had understood it.
> 
> What's happening (in English):
> - If map doesn't have the metadata, load the metadata
> - Put the metadata in the map atomically, while (in the same atom) checking that it wasn't set in the meantime
> - If it was indeed set in the meantime get what was set
</details>
I just had a chat with @hagbard (Thanks!) Interesting stuff :)

So, we're checking above "if (metadata != null)"; we only proceed with loading if metadata isn't already in the map.
So by the time we get to the last line in this method, if oldValue isn't null then we had at least 2 threads go through the loading, and one thread "won" and their loaded object is in the map. The reasons we return that object rather than the one this thread loaded are:
(1) We want to honor the "load that won"
(2) Idiomatically, we want getMultiFileMetadata to return the *same object* to anyone who passes in the same key and map, not just "objects that are equal"; and indeed, an object that's in the map
(3) We want the object/s that didn't get into the map to be promptly garbage collected.

FWIW: What I said earlier about possibly returning to the thread early due to the return value already being computed does not apply here, but might with double locking IUUC. Anyway, that was just me speculating (I failed the interview!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by lararennie** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 119 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_W5R-yCWFcVODCIr_:-KVfP57pz2qBNzzsl_ad:b-a3qex1) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L119)):*
<details><summary><i>Previously, keghani (Keghani Kouzoujian) wrote…</i></summary>
> I just had a chat with @hagbard (Thanks!) Interesting stuff :)
> 
> So, we're checking above "if (metadata != null)"; we only proceed with loading if metadata isn't already in the map.
> So by the time we get to the last line in this method, if oldValue isn't null then we had at least 2 threads go through the loading, and one thread "won" and their loaded object is in the map. The reasons we return that object rather than the one this thread loaded are:
> (1) We want to honor the "load that won"
> (2) Idiomatically, we want getMultiFileMetadata to return the *same object* to anyone who passes in the same key and map, not just "objects that are equal"; and indeed, an object that's in the map
> (3) We want the object/s that didn't get into the map to be promptly garbage collected.
> 
> FWIW: What I said earlier about possibly returning to the thread early due to the return value already being computed does not apply here, but might with double locking IUUC. Anyway, that was just me speculating (I failed the interview!)
</details>
OK thanks for the explanation!!

---

*[java/libphonenumber/test/com/google/i18n/phonenumbers/MetadataManagerTest.java, line 26 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_Y8ae_S0GdW9UO1x8:-KVfPfUDnK9XbiG4Ykw-:baa6kl5) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/test/com/google/i18n/phonenumbers/MetadataManagerTest.java#L26)):*
<details><summary><i>Previously, keghani (Keghani Kouzoujian) wrote…</i></summary>
> Changed to be without final. MetadataFilterTest was the only existing test file with "final class".
> 
> FWIW We do have test files that we ourselves extend, like https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/test/com/google/i18n/phonenumbers/TestMetadataTestCase.java.
</details>
OK

But that class doesn't end in Test.java ;) get your point though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by lararennie** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[java/pending_code_changes.txt, line 7 at r3](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KVjfaZpfJELkhSMBeEu:-KVjfaZpfJELkhSMBeEv:bib1rg5) ([raw file](https://github.com/googlei18n/libphonenumber/blob/6424035c7d3620fc7f9f822e0d9dbbfaeffec15d/java/pending_code_changes.txt#L7)):*
> ```
>  - Refactored metadata loading and removed synchronization for all kinds of
>    metadata. Clients may experience quicker loading of alternate formats and
>    short number metadata, but no change is required for callers of the library.
> ```

Testing 

---

*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 101 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VduENbcTossiYdhl:-KVjevWj497Ywj9EE2g3:b-7fmc6y) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L101)):*
<details><summary><i>Previously, keghani (Keghani Kouzoujian) wrote…</i></summary>
> They're not always already loaded; if already loaded we return, if not we load asynchronously, and once we've loaded we set it atomically if it's still unset by then.
> The user of the API has to pass in the map that they want to contain the key.
</details>
Yep, but my comment was supposed to mean any that *were* already loaded. Because if we have loaded one file, this map has one file in it, and then as we add another file, we pass it in and it adds that file to it too?  My point is: it might not be empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by keghani** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[java/pending_code_changes.txt, line 7 at r3](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KVjfaZpfJELkhSMBeEu:-KVjfp2natWk6Fyd60nr:b-896fix) ([raw file](https://github.com/googlei18n/libphonenumber/blob/6424035c7d3620fc7f9f822e0d9dbbfaeffec15d/java/pending_code_changes.txt#L7)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> Testing 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by lararennie** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[java/pending_code_changes.txt, line 7 at r3](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KVjfaZpfJELkhSMBeEu:-KVjg117jDSzCcSwgUJj:b-vhkcs5) ([raw file](https://github.com/googlei18n/libphonenumber/blob/6424035c7d3620fc7f9f822e0d9dbbfaeffec15d/java/pending_code_changes.txt#L7)):*
<details><summary><i>Previously, keghani (Keghani Kouzoujian) wrote…</i></summary>
> Done.
</details>
Testing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by lararennie** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[java/pending_code_changes.txt, line 9 at r3](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KVjg6Uc-qdIppzkjM1F:-KVjg6Uc-qdIppzkjM1G:b-vhkcs5) ([raw file](https://github.com/googlei18n/libphonenumber/blob/6424035c7d3620fc7f9f822e0d9dbbfaeffec15d/java/pending_code_changes.txt#L9)):*
> ```
>    short number metadata, but no change is required for callers of the library.
>  - Using new possibleLengthInfo to decide whether a short number is the right
>    length or not. This could result in more specific results; whereas before, a
> ```

Testing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by keghani** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[java/pending_code_changes.txt, line 9 at r3](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KVjg6Uc-qdIppzkjM1F:-KVjgE3-DzZlUSGSDVCG:b32w0x) ([raw file](https://github.com/googlei18n/libphonenumber/blob/6424035c7d3620fc7f9f822e0d9dbbfaeffec15d/java/pending_code_changes.txt#L9)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> Testing
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by lararennie** [comment]
Reviewed 3 of 8 files at r1, 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by keghani** [comment]
*[java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, line 101 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411#-KV_VduENbcTossiYdhl:-KVjjfAxrLckmjwZIXlA:b-pn6obz) ([raw file](https://github.com/googlei18n/libphonenumber/blob/95621d931915e9caf167974e1b59b4aad5321a22/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L101)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> Yep, but my comment was supposed to mean any that *were* already loaded. Because if we have loaded one file, this map has one file in it, and then as we add another file, we pass it in and it adds that file to it too?  My point is: it might not be empty.
</details>
Oh I see! So it doesn't "only" contain those mappings. I added your language (mostly - from their key, not to) and added an extra sentence to explain, WDYT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1411)*

**Comment by keghani** [comment]
cpp-build jar is unchanged.
Committed java-build jar, pkgdiff results are in the first comment of the PR.

**Comment by keghani** [comment]
@lararennie Anything left for me to do here? I addressed the comments, ran tests, generated files...

**Pull request merged**
