### PR TITLE
Delete obsolete resources

### PR DESCRIPTION
**Pull request by dlyongemallo**
This should fix issue #936.

### CODE REVIEW

**Comment by keghani** [comment]
Thanks! I'll review after completing the release.

**Comment by keghani** [comment]
Please remove deleted files from this PR - we'll run build.xml for the next release and update all files in one go.

**Comment by keghani** [comment]
Also - let's do another PR to ensure that obsolete short / phone number metadata files are also deleted.

**Comment by keghani** [comment]
When testing this I also get these 2 files:
```
java/carrier/src/com/google/i18n/phonenumbers/carrier/data/config
java/geocoder/src/com/google/i18n/phonenumbers/geocoding/data/config
```
Is this expected? Are they to be checked in?

**Comment by dlyongemallo** [comment]
I've removed the actual file deletion from this PR.

**Comment by keghani** [comment]
Thanks!

**Comment by keghani** [comment]
Released and verified in 7.2.4

**Pull request merged**
