### PR TITLE
Throw errors instead of strings

### PR DESCRIPTION
**Pull request by ruimarinho**
Modified the javascript port to throw errors instead of strings.

### CODE REVIEW

**Comment by jias0001** [comment]
Sorry, cannot accept this, as it changes the public interface and can break clients' code which relies on the method throwing strings.

**Comment by ruimarinho** [comment]
@jias0001 would it be possible to accept this merge when releasing v8.0.0?

**Comment by jias0001** [comment]
We don't want to change the public API unless there is a very good reason behind it, because it requires all clients to update their code. This change doesn't seem to be something that is worth the trouble of all clients updating their code.

**Comment by ruimarinho** [comment]
@jias0001 on PR https://github.com/googlei18n/libphonenumber/pull/595 you mentioned *I remember sometime last year we have updated our code to mostly throwing Error instead of string. Please feel free to send us a patch to update the rest if they are missed from that update.*.

Since this change won't be accepted due to BC concerns, then maybe the npm module being listed could be re-considered? It can become quite frustrating to debug errors thrown as strings.

**Comment by ruimarinho** [comment]
Superseded by https://github.com/googlei18n/libphonenumber/pull/1459.

**Pull request closed without merging**
