### PR TITLE
Area code for mobile phones in brazil

### PR DESCRIPTION
**Pull request by pappacena**
In Brazil, mobile phone numbers also have area code associated with them. I just added a test case, and put the specific check for Brazil on `isNumberGeographical` method.

_Ps.: I proposed this change on Python port of the lib (https://github.com/daviddrysdale/python-phonenumbers/pull/73), and they suggested me to propose for the Java lib instead_

### CODE REVIEW

**Comment by keghani** [comment]
Thanks @pappacena! I'd like to solve a number of other regions in one go, and keep the C++ and JS APIs consistent. It's a bit involved so hard to review as a PR, but I'll give it a shot myself sometime this week. I filed #990.

**Comment by pappacena** [comment]
Hi, @keghani ! If you have the rules for the other regions, let me know and I can help you with that. :-)

Then, I can help changing the C++ and JS APIs as well.

**Comment by keghani** [comment]
Thanks for your support @pappacena :)
I'm working with the team to get this out in the next release. Thanks for your patience!
Indonesia turned out not to be relevant for this change anymore, but I'm adding Argentina and Mexico.

I'm going to close this pull request and track the issue at #990.

**Comment by keghani** [comment]
Hi again,

Just to set expectations - this is unlikely to be in the next release as I have less time than usual given the Easter holidays. I'm targeting the one after. Many thanks for your patience.

**Comment by pappacena** [comment]
Ok, @keghani. Don't worry.

Just let me know if you want any contribution :-)

**Comment by padmaksha** [comment]
Fixed in release 7.3.0

**Pull request closed without merging**
