### PR TITLE
Change build rules to stop mobile and fixed-line descs inheriting from the generalDesc element

### PR DESCRIPTION
**Pull request by keghani**
Metadata changes:
-- Drops the "-1" that was erroneously included in possible lengths before (didn't break anything, but was wrong) - it was a possibleLength of a sub-component so got added to the generalDesc possibleLengths
-- possibleNumberPattern no longer inherited: we don't use this anyway, we will do another CL soon to stop including it at all in the generated metadata
-- exampleNumber is no longer set on fixed-line and mobile elements from the generalDesc

XML file changes:
-- Stopped specifying "NA" and "-1" specifically for fixed-line and mobile blocks; now they are treated as every other type of phone number: if missing, don't fill them in from generalDesc, but leave them missing.

Code changes:
-- Stop using the exampleNumber on generalDesc for non-geo entities, but look at their phonenumber descs - the exampleNumber won't be stored on the generalDesc anymore. This affects porters if they either copied our build logic or used our built metadata in some way; they should update this method in their port too.

************** Do not copy into final commit **************

See https://github.com/googlei18n/libphonenumber/pull/1422 for original review.

Taking over as 2 of the followup commits there were committed with non-CLA addresses although author has signed CLA with other addresses.

Jar diffs:

~keghani/GitHub_diffs/PR1427/pkgdiff_reports/master_cpp/build_to_build/changes_report.html
~keghani/GitHub_diffs/PR1427/pkgdiff_reports/master_java/build_to_build/changes_report.html

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1427)

### CODE REVIEW

**Comment by andyst** [comment]
I'd copy and paste the original commit message rather than having the "See ..."

**Comment by keghani** [comment]
Actually since I'm doing this, I'll also update the jars in this PR.
Please don't merge! Feel free to look though, it'll just be another commit with 2 jars. Diff coming up.

**Comment by keghani** [comment]
Done re. PR description - this doesn't have to be the final commit message though.

**Comment by keghani** [comment]
Jar diffs:

~keghani/GitHub_diffs/PR1427/pkgdiff_reports/master_cpp/build_to_build/changes_report.html#InformationFiles
~keghani/GitHub_diffs/PR1427/pkgdiff_reports/master_java/build_to_build/changes_report.html

All ready!

**Comment by andyst** [comment]
Reviewed all non-binary diffs. LGTM

**Comment by lararennie** [comment]
Thanks ;)

8. nov. 2016 3.56 p.m. skrev "Keghani Kouzoujian" <notifications@github.com

**Pull request merged**
