### PR TITLE
Remove duplicate North Khorasan in Iran comments

### PR DESCRIPTION
**Pull request by afarsi**
I removed duplicate entries of North Khorasan from Iran section's comments.
I requested and Behdad Esfahbod removed it from 98.txt in geocoding folder few months ago. For more info look at https://github.com/googlei18n/libphonenumber/pull/1185 and https://github.com/googlei18n/libphonenumber/pull/1155
I saw those duplicates are remained here yet! I think in continue of that, we should remove duplicates from PhoneNumberMetaData comments.

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1418)

### CODE REVIEW

**Comment by lararennie** [comment]
If we remove it from the comments, should we not also change the prefix? We still accept numbers with the prefixes 57 and 64. Or are those prefixes used for something else?

**Comment by afarsi** [comment]
Hi @lararennie 
If you look at official latest [itu doc for iran](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000660003PDFE.pdf), then you will see there is not any 57 and 64 NDC. Now 57 and 64 haven't any usability. North Khorasan have only one NDC which is 58.

Using 57 and 64 was for migration process from old numbering plan to new numbering plan. You shouldn't accept any number with prefix 57 and 64. I think by https://github.com/googlei18n/libphonenumber/pull/1185 and https://github.com/googlei18n/libphonenumber/pull/1155 (merged), now libphonenumber don't accept these prefixes.

**Comment by lararennie** [comment]
Sadly it still does. Can you edit the regex immediately below in this file
to remove those two prefixes?

3. nov. 2016 6.06 p.m. skrev "Amir Farsi" <notifications@github.com>:

**Comment by afarsi** [comment]
Unfortunately, I don't know anything about how those sections(Like Line 12113 and 12114) working? Why I should change them? What is relation between those lines and acceptation of 57 and 64 NDCs? I couldn't find 57 or 64 in those lines! As result, please change them your self.

But Please describe the structure and meaning of codes between <nationalNumberPattern> tags line by line. This descriptions will help to me for better understanding and better contribution in feature.

 <nationalNumberPattern>


           (?:


             1[137]|


             2[13-68]|


             3[1458]|


             4[145]|


             5[146-8]|


             6[146]|


             7[1467]|


             8[13467]


           )\d{8}


         </nationalNumberPattern>

Thanks.

**Comment by lararennie** [comment]
Ok, then please close this PR and file a normal issue and we will deal with
it - easier. Or otherwise just make the two edits I say ;)

More detailed explanations inline below.

3. nov. 2016 6.57 p.m. skrev "Amir Farsi" <notifications@github.com>:
>
> Unfortunately, I don't know anything about how those sections(Like Line
12113 and 12114) working? Why I should change them? What is relation
between those lines and acceptation of 57 and 64 NDCs? I couldn't find 57
or 64 in those lines! As result, please change them your self.
>
> But Please describe the structure and meaning of codes between tags line
by line. This descriptions will help to me for better understanding and
better contribution in feature.
>
>  (?: 1[137]|

Prefixes 11, 13 and 17 OR (the | symbol)

2[13-68]|

Prefixes 21, 23, 24, 25, 26, 28 (the - is a range)

Etc

3[1458]| 4[145]| 5[146-8]| 6[146]| 7[1467]| 8[13467] )\d{8}
</nationalNumberPattern>

**Comment by afarsi** [comment]
@lararennie Thank you for your very good description about the meaning of codes between nationalNumberPattern tags. I understood the meaning of them completely!

I Updated that file based on your request. As result I think now libphonenumber don't accept 57 and 64.
Please check changes and if it's ok, commit the changes.

**Pull request merged**
