### PR TITLE
Create 30.txt

### PR DESCRIPTION
**Pull request by greatslon**
New geocoding file

### CODE REVIEW

**Comment by greatslon** [comment]
I signed it!

**Comment by kkeshava** [comment]
@greatslon,
Thank you for contributing to libphonenumber!
We need official evidence to accept the geocoding updates you have made. Please see our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
Hi,
Please update the copyright / license header in the new metadata files to match exactly what we have in other metadata files ('The Libphonenumber Authors' and Apache License, version 2.0).

**Comment by kkeshava** [comment]
This issue is blocked on your input. Please help us find evidence for geocoding updates. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.

**Pull request closed without merging**
