### PR TITLE
Update 375.txt

### PR DESCRIPTION
**Pull request by greatslon**
Geocoding updates

### CODE REVIEW

**Comment by greatslon** [comment]
I signed it!

**Comment by kkeshava** [comment]
@greatslon,
Thank you for contributing to libphonenumber!
We need official evidence to accept the geocoding updates you have made. Please see our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
@greatslon,
Before we can accept the change, we need you to undo the changes to the copyright line to be consistent with the rest of the project. You may update the year though. It must say '# Copyright (C) <year> The Libphonenumber Authors', where <year> should be the current year. 
375.txt has an inconsistent copyright line right now i.e 'Google Inc' so we will be fixing it and changing it to 'The Libphonenumber Authors'.

**Comment by kirstenhgarcia002** [comment]
Delete update

**Comment by kkeshava** [comment]
This issue is blocked on your input. As mentioned earlier we need official evidence to accept the geocoding updates you have made. Please see our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).
Please undo the changes to the copyright line to be consistent with the rest of the project. You may update the year though. It must say '# Copyright (C) The Libphonenumber Authors', where should be the current year. Also please retain other information that is placed below the copyright line.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.

**Pull request closed without merging**
