### PR TITLE
Minor rewording for clarification

### PR DESCRIPTION
**Pull request by dantwining**
Attempted to clarify the wording around the 800 country code, which is distinct from the 800 area code, and was initially confusing (to me).

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1413)

### CODE REVIEW

**Comment by dantwining** [comment]
I signed it!

**Comment by lararennie** [comment]
:lgtm: Thanks! Can you also make the same change for the 8th falsehood that refers to 00800 numbers?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1413#-:-KVVj8U69X6tc8Rx9reK:b-ede8oj)*

**Comment by lararennie** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1413#-:-KViCmDUrjvZfPTqgXjJ:bnfp4nl)*

**Comment by lararennie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1413)*

**Pull request merged**
