### PR TITLE
+43 828 can be followed by five or more digits

### PR DESCRIPTION
**Pull request by DrHyde**
This fixes https://github.com/googlei18n/libphonenumber/issues/841.

+43 828 followed by five or more digits is valid. +43 820 or 821 must still be followed by at least six.

### CODE REVIEW

**Comment by DrHyde** [comment]
Is there anything else I need to do to get this merged?

**Comment by mihaelacr-google** [comment]
Please ensure you align the 1 under the '?' when formatting the regex. We try to keep that style in the metadata.

**Comment by DrHyde** [comment]
Done!

**Comment by mihaelacr-google** [comment]
Thanks! Another comment. Can you group the 82 ranges together? That makes it easier to follow if we keep the nested structure. 

I came up this regex which expresses allows the same strings but is a bit less repetitive:

```
   8(?:
     10\d|
     2(?:
       [01]\d|
       8\d?
      )
    )\d{5,9}
```

**Comment by DrHyde** [comment]
Done! (again :-)

**Comment by mihaelacr-google** [comment]
Also need to ensure that the possibleNumberPattern is updated to: 

<possibleNumberPattern>\d{8,13}</possibleNumberPattern>

**Comment by DrHyde** [comment]
Also done. Didn't spot that because my code doesn't use it.

**Pull request merged**
