### PR TITLE
README: Use syntax highlighting for code blocks

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by andyst** [comment]
Thanks!

**Comment by andyst** [comment]
@Turbo87 
Have you signed the CLA? If not, please sign it. We'd have to remove the patch again otherwise.

https://github.com/googlei18n/libphonenumber/wiki/ContributeToTheProject

Thanks!

**Comment by Turbo87** [comment]
Thanks for reminding me, I just signed it. Let me know if there are any
other issues.

**Comment by andyst** [comment]
Thanks!

**Pull request merged**
