### PR TITLE
Allow commas in extensions

### PR DESCRIPTION
**Pull request by voronaam**
Fixes issue #467 for Java.

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1706)

### CODE REVIEW

**Comment by voronaam** [comment]
I signed it! (the CLA)

**Comment by voronaam** [comment]
Internal JIRA reference: ARCH-5875

**Comment by keghani** [comment]
Thanks for the pull request @voronaam!

This is unfortunately not enough. As @lararennie mentioned at #467, we need to research if people are using commas to "wait", and we need to have a signal so that we don't allow commas when detecting numbers in text. We can't prioritize working on or reviewing this anytime soon, thanks for understanding.

**Comment by voronaam** [comment]
I am "people" and work for a company whose end users use commas in extenstions for wait signal.
What kind of research would you need?

**Comment by keghani** [comment]
E.g. whether some users (internationally) use this notation to indicate 2 separate numbers - see @lararennie's question at #467. We don't want to make a change in the library that would work for some users but break others.

**Comment by voronaam** [comment]
I posted comments to issue #467 I think it is best to keep conversation in there.

**Pull request closed without merging**
