### PR TITLE
update mobile phone location and carrier identification data for China, ...

### LINKED ISSUE #608: Add China prefix 149
Currently I am using this project to normalize domestic phone number, while I found that I cannot handle some phone numbers with prefix 149. I cannot get its carrier in English. 
2) What's more, I cannot get the carrier in Chinese for all the mobile Phone numbers in China. 
3) The location file is not up to date and need to be updated.

### PR DESCRIPTION
**Pull request by chaoaero**
...fixes #608

### CODE REVIEW

**Comment by andyst** [comment]
Have you signed the contributor agreement already?
https://github.com/googlei18n/libphonenumber/wiki/ContributeToTheProject

Thanks!

**Comment by chaoaero** [comment]
Thanks for your notice. I have signed it. Please review my submission.

**Comment by keghani** [comment]
Thanks @chaoaero! We recently did a complete revision of the China metadata, but we will look at this patch and apply anything we may have missed out.
We stopped accepting PRs for metadata updates but we have no document to reference for this request, so I'm keeping it open to reference the changes.

**Comment by keghani** [comment]
Closing this PR.

*   We aren't adding 149 because nothing has changed since we closed issue #608.
*   Carrier data has been updated in the meantime.
*   We will update the extra geographical data ourselves, and reference it as being contributed by you in the metadata file.

**Comment by lararennie** [comment]
Ah, just noticed the extra geographical data is also for this prefix.
Okay, when/if the prefix starts getting used in real life we will update it and reference it as your contribution :)

**Comment by chaoaero** [comment]
ok

2017-07-14 16:52 GMT+08:00 lararennie <notifications@github.com>:

**Pull request closed without merging**
