### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by akfernun**
The currently listed ruby port is no longer maintained. The repo listed is actively maintained and used in production.

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1652)

### CODE REVIEW

**Comment by keghani** [comment]
Closed an re-opened to kick off the automatic checks :)

**Comment by keghani** [comment]
Thanks for your pull request.  It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit <https://cla.developers.google.com/> to sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify.  Thanks.

---

- If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
- If you signed the CLA as a corporation, please let us know the company's name.

**Comment by keghani** [comment]
@akfernun, sorry for the delay and thanks for your contribution!
I was expecting the CLA checks to kick off automatically but they didn't.

If you could sign the CLA and update your branch with the latest changes from master I could merge this.
(If this happens next week or someone else merges in the meantime, chances are you'll have to update your branch again because we don't merge into master during the release; I expect we'll start on that next Tuesday or so).

**Comment by akfernun** [comment]
I signed it!

**Comment by keghani** [comment]
Great, thanks!

**Pull request merged**
