### PR TITLE
Update 386.txt

### PR DESCRIPTION
**Pull request by skymania**
The 2 operators names have changed, Mobitel to Telekom Slovenije and Tušmobil to Telemach.

### CODE REVIEW

**Comment by skymania** [comment]
I signed it!

**Comment by skymania** [comment]
@penmetsaa 
Only those with write access to this repository can merge pull requests.

**Comment by penmetsaa** [comment]
Oh ok. Sorry!
I have merged it now :)

**Comment by skymania** [comment]
Thnx man ;)

**Pull request merged**
