### PR TITLE
Complete 170x VNOs range of Chinese carrier data

### PR DESCRIPTION
**Pull request by felixonmars**
The data could be found on Wikipedia:
https://en.wikipedia.org/wiki/Telephone_numbers_in_China#Mobile_phones

### CODE REVIEW

**Comment by kkeshava** [comment]
@felixonmars,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by felixonmars** [comment]
Updated accordingly :)

**Comment by felixonmars** [comment]
Changed accordingly. But actually some 170x ranges are also assigned to China Telecom and China Mobile, that's why I removed the mention to China Unicom and used "major carriers".

**Comment by felixonmars** [comment]
Made some small adjustments to list all three for 86170. Hopefully it's okay :P

**Comment by kkeshava** [comment]
Thanks, could you please update  your branch and merge it.

**Comment by felixonmars** [comment]
Done :)

**Pull request merged**
