### PR TITLE
Added Czech republic municipal police emergency number

### PR DESCRIPTION
**Pull request by randomf**
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1666)

### CODE REVIEW

**Comment by randomf** [comment]
I signed it!

**Comment by randomf** [comment]
I signed it!

**Comment by kkeshava** [comment]
Hi,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed as part of release 8.4.1
https://libphonenumber.appspot.com/phonenumberparser?number=156&country=CZ

**Pull request closed without merging**
