### PR TITLE
Test filter metadata

### PR DESCRIPTION
**Pull request by keghani**
** do not copy into final commit **

cl/139562073

pkgdiff:
~keghani/GitHub_diffs/PR1437/pkgdiff_reports/cpp-build/1.0-SNAPSHOT-jar-with-dependencies_to_1.0-SNAPSHOT-jar-with-dependencies/changes_report.html
~keghani/GitHub_diffs/PR1437/pkgdiff_reports/java-build/1.0-SNAPSHOT-jar-with-dependencies_to_1.0-SNAPSHOT-jar-with-dependencies/changes_report.html

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1437)

### CODE REVIEW

**Comment by lararennie** [comment]
So we don't need to do anything in the poms to get junit4 tests to run as well as non-junit4? That's nice! Do you have a link of the test results to show they were run?

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/java/common/test/com/google/i18n/phonenumbers/MetadataFilterTest.java, line 939 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1437#-KWrAf3XUQecxmucn7M3:-KWrAf3YM2GO_7uymp23:b-nhubaz) ([raw file](https://github.com/googlei18n/libphonenumber/blob/08874937cd393e78dd6516eb5637233f02a5b180/tools/java/common/test/com/google/i18n/phonenumbers/MetadataFilterTest.java#L939)):*
> ```Java
>     assertEquals(metadata.getId(), "AM");
>     assertEquals(metadata.getCountryCode(), 374);
>     assertEquals(metadata.getInternationalPrefix(), "0[01]");
> ```

Why are these vars not also constants like NATIONAL_NUMBER_PATTERN and EXAMPLE_NUMBER?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1437#-:-KWrAsSrPK-1yEUydj03:bv46l9q)*

**Comment by keghani** [comment]
*[tools/java/common/test/com/google/i18n/phonenumbers/MetadataFilterTest.java, line 939 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1437#-KWrAf3XUQecxmucn7M3:-KWrVeHr5zEW85TwkuXM:b5gfhlh) ([raw file](https://github.com/googlei18n/libphonenumber/blob/08874937cd393e78dd6516eb5637233f02a5b180/tools/java/common/test/com/google/i18n/phonenumbers/MetadataFilterTest.java#L939)):*
<details><summary><i>Previously, lararennie wrote…</i></summary>
> Why are these vars not also constants like NATIONAL_NUMBER_PATTERN and EXAMPLE_NUMBER?
</details>
I guess because they weren't in the last review and my diff didn't catch this :)
I want to make these consistent and move on, been back and forthing on these files for a while, do you mind if we let them be for now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1437)*

**Comment by lararennie** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/java/common/test/com/google/i18n/phonenumbers/MetadataFilterTest.java, line 939 at r1](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1437#-KWrAf3XUQecxmucn7M3:-KWrWfEyY0eZ93thiA8C:bevvk0v) ([raw file](https://github.com/googlei18n/libphonenumber/blob/08874937cd393e78dd6516eb5637233f02a5b180/tools/java/common/test/com/google/i18n/phonenumbers/MetadataFilterTest.java#L939)):*
<details><summary><i>Previously, keghani (Keghani Kouzoujian) wrote…</i></summary>
> I guess because they weren't in the last review and my diff didn't catch this :)
> I want to make these consistent and move on, been back and forthing on these files for a while, do you mind if we let them be for now?
</details>
I don't mind, it's not a biggy, just slightly odd :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1437)*

**Comment by keghani** [comment]
Finally, yes :) ~keghani/GitHub_diffs/PR1437_test_results/surefire-reports/
Did you want to see something else? I couldn't share all the test output, it's too big to copy the whole thing but I could copy specific files/directories.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/googlei18n/libphonenumber/1437#-:-KWrd_icyg8d9T-TDqIb:bm48rdc)*

**Comment by keghani** [comment]
Re. junit4 being usable without additional dependencies, I think that might be because we already have these:

Maven:
https://github.com/googlei18n/libphonenumber/blob/aacfaad3a84947ebde2b2994ca2c76e9f1ac1380/tools/java/common/pom.xml#L58
https://github.com/googlei18n/libphonenumber/blob/0068d861a68d3d4612f7bf8646ab844dd3cefce5/tools/java/data/pom.xml#L33
https://github.com/googlei18n/libphonenumber/blob/aacfaad3a84947ebde2b2994ca2c76e9f1ac1380/tools/java/java-build/pom.xml#L110
https://github.com/googlei18n/libphonenumber/blob/9211191e3559cc9fc35d3113092d8fd91afc4d1c/java/pom.xml#L198
https://github.com/googlei18n/libphonenumber/blob/aacfaad3a84947ebde2b2994ca2c76e9f1ac1380/tools/java/cpp-build/pom.xml#L150

Ant:
https://github.com/googlei18n/libphonenumber/blob/master/java/build.xml#L27
https://github.com/googlei18n/libphonenumber/blob/master/java/lib/junit-4.8.1.jar

**Pull request merged**
