### PR TITLE
Including the ninth digit of Brazil in DDD's 31, 32, 33, 34, 35, 37 and 38 (State of Minas Gerais). 71, 73, 74, 75 and 77 (State of Bahia). 79 (State of Sergipe)

### PR DESCRIPTION
**Pull request by SavioOliveira**

### CODE REVIEW

**Comment by dlyongemallo** [comment]
This change is insufficient for the desired effect. It only changes formatting, but not validation (see the mobile pattern).

We are already working on this, and it should be out in the next release.

**Comment by SavioOliveira** [comment]
Thank you for your response, I await the next release :)

**Comment by robertamoreira** [comment]
@dlyongemallo Could you please give us a reference of the method (file) that validates the mobile pattern? We use google-libphonenumber in our project and this modification is kinda urgent to us (I'm asking because we would like to try to work on this issue until the next release comes, due to the urgency of the project).

**Comment by dlyongemallo** [comment]
See this commit:
https://github.com/googlei18n/libphonenumber/commit/7c2de0119cd461c90bd37b59b9bb317c05a56bef

**Comment by robertamoreira** [comment]
Many thanks, @dlyongemallo!

**Comment by rafaelschettino** [comment]
@dlyongemallo When the new release including Brazil changes will be released?

**Comment by rafaelschettino** [comment]
@dlyongemallo I'm a bit worried because the Brazil (ANATEL Government Agency) will insert this new digit in a lot of cellphone numbers on the next weekend.

**Comment by dlyongemallo** [comment]
The release of the next version should be taking place this week.

**Comment by dlyongemallo** [comment]
This was just released in 7.1.0.

**Pull request closed without merging**
