### PR TITLE
add js port to readme

### PR DESCRIPTION
**Pull request by avimar**
Full JavaScript port, with regular updates (this is what I use server-side)

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1564)

### CODE REVIEW

**Comment by lararennie** [comment]
How does this one differ from ours?

8. feb. 2017 8.46 p.m. skrev "avimar" <notifications@github.com>:

**Comment by avimar** [comment]
1) It's install-able by NPM
2) it's browserify-compatible for client-side usage, too.
3) I actually have no clue how to use your javascript myself. Most of the .js files seem to have a ton of `goog.require()` and I don't know what that depends on.

He used to also patch errors into normalized javascript errors, but you've fixed that.

**Comment by lararennie** [comment]
3. It uses Closure. Have you read the README, including info on how to setup, and how to use?
https://github.com/googlei18n/libphonenumber/blob/master/javascript/README.md

If we were going to advertise this, we would need the README to concisely say for whom it is appropriate.

**Comment by avimar** [comment]
Oh wow. Nope, I haven't read that -- I only saw the root readme!

Wow. That's complicated setup. seegno is already compiled to vanilla JS as a SINGLE dependency without needing everything else first.

**Comment by lararennie** [comment]
Well, the linter is optional :)
And the idea is that you'd use closure on your whole project, not just libphonenumber, and it makes it *all* smaller, and checks it for you.

**Comment by lararennie** [comment]
Superseded by PR#1714, marking as closed :) Thanks for bringing this to our attention!

**Pull request closed without merging**
