### PR TITLE
Somalia: added support for 62, 65, 66 Somtel codes

### PR DESCRIPTION
**Pull request by tadixas**

### CODE REVIEW

**Comment by jias0001** [comment]
Thanks for sending the pull requests! Do you have supporting evidence for the change?

Also, have you signed the CLA for making contributions?

**Comment by tadixas** [comment]
Well we are using ported Python library and in current project we got complains that some numbers from Somalia are not accepted. We got explanation that 62 65 66 codes are valid and belong to Somtel. What would be proper evidence? I could try to get it if needed.

Sorry, it may sound silly, but what is CLA? :) If I was not allowed to make pull request, sorry for inconvenience, it will not recur again.

**Comment by jias0001** [comment]
We welcome and appreciate contributions like this! CLA is a Contributor License Agreement which every contributor to the project needs to sign. It is quite simple to do it. This is explained under section 4 of the following document: 

https://github.com/googlei18n/libphonenumber/wiki/ContributeToTheProject 

For evidence, any official documentation from the government, telecom authority or carriers are good. Most of the contributors provide IR21 doc, which is provided directly from the carrier. If none of them is available, news reports of the introduction of the new prefixes also work.

**Comment by keghani** [comment]
Fixed in release 7.0.11.

**Pull request closed without merging**
