### PR TITLE
Telenor MM new range

### PR DESCRIPTION
**Pull request by alecx**
Telenor Myanmar introduced a new number series in market starting with
+95978.

### CODE REVIEW

**Comment by andyst** [comment]
Thanks for the report! Added to our internal bug triage queue. There are currently a lot of updates (also from ITU), so it might take a bit longer.

**Comment by andyst** [comment]
Was a bit fast there...

Do you have any evidence (government or from the telco) for this change?

**Comment by roes** [comment]
This will be part of the next release

**Comment by andyst** [comment]
This change is in libphonenumber 7.0.6 which we released a few weeks ago.

**Pull request closed without merging**
