### PR TITLE
Change brazilian prefix - add 9 digit

### PR DESCRIPTION
**Pull request by fabianomichels**
Add digit 9 to adapt new mobile prefix.

Until now, only 551X and 552X is correct.

http://www.anatel.gov.br/institucional/component/content/article?id=1385
http://www.anatel.gov.br/setorregulado/index.php/nono-digito

---
This change is [Reviewable](https://reviewable.io/reviews/googlei18n/libphonenumber/1537)

### CODE REVIEW

**Comment by keghani** [comment]
Hi! Sorry we didn't respond to this earlier, we were actually tracking it at https://github.com/googlei18n/libphonenumber/issues/1284 and it will be fixed in the next release.

**Comment by GuilhermeCouto** [comment]
Was it released? Its not working for me if I try, for example, 44999999999

**Comment by lararennie** [comment]
http://libphonenumber.appspot.com/phonenumberparser?number=44999999999&country=BR
Yes.

**Comment by lararennie** [comment]
Send an email to the discussion list with details of your problem, and people can help you there.

**Comment by avnermiz** [comment]
Your Brazil numbers are out of date.  Ten digit numbers starting with 819 are valid mobile numbers, but the phone lib says they are invalid.  See: 

https://libphonenumber.appspot.com/phonenumberparser?number=8199123456&country=BR

**Pull request closed without merging**
