### PR TITLE
fix bug with nationalPrefixOptionalWhenFormatting being dropped for the US when writing nanoproto files

### PR DESCRIPTION
**Pull request by dlyongemallo**

### CODE REVIEW

**Comment by keghani** [comment]
Should do removal of the conditional in the existing (regular proto) code to ensure tests pass and metadata doesn't change.

**Comment by dlyongemallo** [comment]
Rendered unnecessary by googlei18n/libphonenumber#883

**Comment by keghani** [comment]
Did you mean by googlei18n/libphonenumber#884 ?

**Comment by keghani** [comment]
Still need to merge though and update js metadata etc.

**Comment by dlyongemallo** [comment]
Yes, of course, I meant googlei18n/libphonenumber#884. :-)

I cherry-picked the change from master. It's effective the same change as this one:
googlei18n/libphonenumber#885

**Pull request closed without merging**
