### PR TITLE
Passing PhoneNumberUtil instance to AsYouTypeFormatter

### PR DESCRIPTION
**Pull request by naveenOnarayanan**
`AsYouTypeFormatter` should use the same `PhoneNumberUtil` instance in order to support `PhoneNumberUtil` instances with custom `MetadataLoader` such as the following:

```java
PhoneNumberUtil util = PhoneNumberUtil.createInstance(new MetadataLoader() {
  @Override
  public InputStream loadMetadata(String metadataFileName) {
    return Application.getContext().getAssets().open("some/asset/path" + metadataFileName);
  }
});
```

### CODE REVIEW

**Comment by naveenOnarayanan** [comment]
I signed it!

**Comment by naveenOnarayanan** [comment]
Ping for review

**Comment by aminghadersohi** [comment]
Any update on this?

**Comment by agongi** [comment]
It looks good but nobody is interested.
plz review this pull request

**Comment by keghani** [comment]
Thanks for this!

Please see the [contribution guidelines for pull requests](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#pull-requests).

We need to think in our team about whether this is something we want to fix right now given other priorities. I would not make any more changes to avoid spending cycles in case we can't accept it.

But in the meantime, it would be great if you could link to an issue as described at the link. And if you could confirm that you'd be willing and able to port the fix to all relevant languages and include tests and be responsive to a code review. There are more details at the link as to what's required of a pull request to be merged.

**Comment by keghani** [comment]
We've thought about this in our team, and realized it's an extension of existing issue #1757.
We'll track the issue there, and we won't accept a PR for it at this time.

As for the issue, please be advised that validation metadata updates are top priority and considering our large backlog we may take a while to fix it.

**Pull request closed without merging**
