### PR TITLE
Update on the 11 numbers rule for Brazil

### PR DESCRIPTION
**Pull request by igorcferreira**

### CODE REVIEW

**Comment by roes** [comment]
Hi,
Could you provide some more information of what you're doing and why? (Including official documentation if available)

**Comment by igorcferreira** [comment]
@roes, Brazil's National Telecommunications Authority (Anatel) has published an updated timetable for the implementation of the ninth digit to mobile phone numbers. From 31 May 2015, mobile phones in Pernambuco, Alagoas, Paraiba, Rio Grande do Norte, Ceara and Piauí will have an extra digit. Those in Minas Gerais, Bahia and Sergipe will get the ninth digit from 11 October 2015.

I'll try to find a translated documentation to link here.

**Comment by davidpaniz** [comment]
Any update on this PR? The new format of phones starting with +558 will be live next Sunday.

**Comment by davidpaniz** [comment]
A few sources I found in english:
http://www.vivo.com.br/consumo/groups/public/documents/vivopw/pw_pdf_oficio_anatel.pdf

https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&ved=0CC4QFjAD&url=https%3A%2F%2Fwww.itu.int%2Fdms_pub%2Fitu-t%2Foth%2F02%2F02%2FT020200001D0001MSWE.docx&ei=0F1jVcS4FciIsQTwk4G4BA&usg=AFQjCNGvVDHzDoyl3HdtDf0GI35EbD2X4g&bvm=bv.93990622,d.cWc&cad=rja

https://www.telegeography.com/products/commsupdate/articles/2015/03/26/anatel-updates-timeframe-for-additional-digit/

http://www.confirmeonline.com.br/confirme/en/noticias/mais-cinco-estados-adotarao-nono-digito-em-celulares-informa-anatel/

**Comment by andyst** [comment]
Thanks, @igorcferreira, we've scheduled this change for this week. It's going to be part of the next libphonenumber release (either this week or next week).

The actual change that we're making looks slightly different (merging some metadata lines).

I'll mark this as closed once the release is out.

**Comment by andyst** [comment]
This change is in libphonenumber 7.0.6 which we released a few weeks ago.

**Pull request closed without merging**
