### PR TITLE
8617* number info update

### PR DESCRIPTION
**Pull request by tg123**
1 add 17* data
2 update some Chinese numbers geo info

### CODE REVIEW

**Comment by jias0001** [comment]
There seems to be many errors in the English files. I did a quick spot check, and notice a number of errors. There are definitely more:

Weihai, Shandong changed to Wehai, Shandong
Baise, Guangxi changed to Bose, Guangxi

There are also lots of insertion of ', which are unnecessary for us. (e.g. XiAn -> Xi'An)

**Comment by tg123** [comment]
hi @jias0001 
my translation is from https://raw.githubusercontent.com/googlei18n/libaddressinput/master/testdata/countryinfo.txt


```
data/CN/广西壮族自治区={"id":"data/CN/广西壮族自治区","key":"广西壮族自治区","lang":"zh-hans","lname":"Guangxi Zhuangzuzizhiqu","isoid":"45","sub_keys":"百色市~北海市~崇左市~防城港市~贵港市~桂林市~河池市~贺州市~来宾市~柳州市~南宁市~钦州市~梧州市~玉林市","sub_lnames":"Bose Shi~Beihai Shi~Chongzuo Shi~Fangchenggang Shi~Guigang Shi~Guilin Shi~Hechi Shi~Hezhou Shi~Laibin Shi~Liuzhou Shi~Nanning Shi~Qinzhou Shi~Wuzhou Shi~Yulin Shi","sub_zipexs":"533000~536000~532200~538001~537100~541002~547000~542800~546100~545001~530012~535000~543000~537000","sub_mores":"true~true~true~true~true~true~true~true~true~true~true~true~true~true"}
```

```
data/CN/山东省={"id":"data/CN/山东省","key":"山东省","lang":"zh-hans","lname":"Shandong Sheng","isoid":"37","sub_keys":"滨州市~德州市~东营市~菏泽市~济南市~济宁市~莱芜市~聊城市~临沂市~青岛市~日照市~泰安市~威海市~潍坊市~烟台市~枣庄市~淄博市","sub_lnames":"Binzhou shi~Dezhou Shi~Dongying Shi~Heze Shi~Jinan Shi~Jining Shi~Laiwu Shi~Liaocheng Shi~Linyi Shi~Qingdao Shi~Rizhao Shi~Tai'an Shi~Wehai Shi~Weifang shi~Yantai Shi~Zaozhuang Shi~Zibo Shi","sub_zipexs":"256619~253012~257093~274020~250001~272119~271100~252052~276001~266001~276800~271000~264200~261041~264001~277101~255039","sub_mores":"true~true~true~true~true~true~true~true~true~true~true~true~true~true~true~true~true"}
```

**Comment by tg123** [comment]
`'` I will remove them.

I just want to find some standard translations for Chinese cities,
then I choose the project also from google i18n. 

Could you please cc this message to `libaddressinput` team?

```
{"lang": "zh", "zipex": "137401", "name": "乌兰浩特市", "lname": "Ulan Hot Shi", "key": "乌兰浩特市", "id": "data/CN/内蒙古自治区/兴安盟/乌兰浩特市"}
```
http://i18napis.appspot.com/address/data/CN/%E5%86%85%E8%92%99%E5%8F%A4%E8%87%AA%E6%B2%BB%E5%8C%BA/%E5%85%B4%E5%AE%89%E7%9B%9F/%E4%B9%8C%E5%85%B0%E6%B5%A9%E7%89%B9%E5%B8%82

I noticed something like that while importing the data. 
and I do not know if all Chinese cities should be named with pinyin in English.
as a result, I choose trusting `libaddressinput`.




--- 

百色 Bose
http://i18napis.appspot.com/address/data/CN/%E5%B9%BF%E8%A5%BF%E5%A3%AE%E6%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA/%E7%99%BE%E8%89%B2%E5%B8%82

威海 Wehai
http://i18napis.appspot.com/address/data/CN/%E5%B1%B1%E4%B8%9C%E7%9C%81/%E5%A8%81%E6%B5%B7%E5%B8%82

**Comment by tg123** [comment]
names in `libaddressinput` but not matching their pinyin

Chinese|libaddressinput|Pinyin
-------|---------------|------
鄂尔多斯市|Ordos|Eerduosi
甘孜藏族自治州|Garzê|Ganzi
克孜勒苏柯尔克孜自治州|Kizilsu|Kezilesukeerkezi
果洛藏族自治州|Golog|Guoluo
巴彦淖尔市|Bayannur|Bayannaoer
克拉玛依市|Karamay|Kelamayi
兴安盟|Hinggan|Xinganmeng
那曲地区|Nagqu|Naqu
乌鲁木齐市|Ürümqi|Wulumuqi
六盘水市|Lupanshui|Liupanshui
呼伦贝尔市|Hulun|Hulunbeier
阿里地区|Ngari|Ali
阿克苏地区|Aksu|Akesu
博尔塔拉蒙古自治州|Bortala|Boertala
伊犁哈萨克自治州|Ili|Yili
文昌市|Qiongshan|Wenchang
阿勒泰地区|Altay|Aletai
拉萨市|Lhasa|Lasa
哈尔滨市|Harbin|Haerbin
吐鲁番地区|Turpan|Tulufan
巴音郭楞蒙古自治州|Bayingolin|Bayinguoleng
林芝地区|Nyingchi|Linzhi
昌都地区|Qamdo|Changdu
日喀则地区|Xigazê|Rikaze
阿拉善盟|Alxa|Alashanmeng
迪庆藏族自治州|Dêqên|Diqing
呼和浩特市|Hohhot|Huhehaote
和田地区|Hotan|Hetian
吕梁市|Lüliang|Lvliang
百色市|Bose|Baise
乌兰察布市|Ulanqab|Wulanchabu
齐齐哈尔市|Qiqihar|Qiqihaer
威海市|Wehai|Weihai
大兴安岭地区|Da|Daxinganling
六安市|Lu'An|Liuan

**Comment by jias0001** [comment]
Thanks for the detailed analysis! Some of the names seem fine, but some
others seem plain wrong. I will let the Dev of libaddress know about this.

It seems your change is about adding new mappings. If you can reuse the
existing names in the en/86.txt file, that would be more consistent and
desirable.

Cheers,

Shaopeng

**Comment by dlyongemallo** [comment]
Thanks for the detailed report! There are indeed a few errors: Weihai, Baise, and Wenchang will be updated to the correct values.

As far as the apostrophe is concerned, we follow the convention used in Google Maps of inserting an apostrophe to break up a pair of adjacent vowels (i.e., to show two distinct vowels as opposed to a diphthong). Thus, we write "Xi'an" rather than "Xian" (like http://en.wikipedia.org/wiki/Xi'an).

Similarly, we use ü rather than v for Lüliang (http://en.wikipedia.org/wiki/Lüliang).

For names which are not Chinese in origin, we use (the Latinised form of) the original name, like "Lhasa", since in most cases this is much more recognisable to English speakers.

For 大兴安岭地区, libaddressinput has "Da Hinggan Ling Diqu", so you probably are dropping everything after a space if you're just getting "Da":
http://i18napis.appspot.com/address/data/CN/黑龙江省/大兴安岭地区

**Comment by tg123** [comment]
@dlyongemallo
sorry, I use awk to make them a table, then ` Hinggan Ling` is missing.

but, `Da Hinggan Ling` or `Da Xingan Ling`?

please notify me after `libaddressinput` was updated, 
and I will update the PR using the lastest data.

**Comment by dlyongemallo** [comment]
The original name is Manchu, and that's the correct Latinised form:
http://en.wikipedia.org/wiki/Da_Hinggan_Ling_Prefecture

**Comment by tg123** [comment]
@jias0001 all have been fixed

Note:

LiuAn (in old en/86.txt) should be LuAn
http://en.wikipedia.org/wiki/Lu%27an

**Comment by jias0001** [comment]
Looks good to me now. Thanks for making the change!

**Pull request merged**
